ALTER TABLE provas ADD COLUMN IF NOT EXISTS prova_url TEXT;
ALTER TABLE provas ADD COLUMN IF NOT EXISTS gabarito_url TEXT;
ALTER TABLE provas ADD COLUMN IF NOT EXISTS edital_url TEXT;
ALTER TABLE provas ADD COLUMN IF NOT EXISTS recurso_url TEXT;
